name: Matrix demo
on:
  push:
    branches:
      - main
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12,14,16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node version
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
