name: Output information
on:
  workflow_dispatch:
    required: false
  issue_comment:
    types: [ created, deleted ]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: |
          echo "Issue comment was created which says:"
          echo "${{ toJSON(github.event.comment.body) }}"
