name: Reusable workflow
on:
  workflow_call:
   inputs:
     artifacts-name:
       description: Input for deployed reusable workflow
       required: false
       type: string
       default: dist
   outputs:
     result:
       description: Output from deploy reusable job
       value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  outputs:
    outcome: ${{ steps.set-result.outputs.step-results }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download the artifacts
        uses: actions/download-artifact@v3
        with:
            name: ${{inputs.artifacts-name}}
      - name: List files
        run: ls -alh
      - name: Deploy
        run: echo "Deploying ..."
      - name: Set output
        run: echo "step-result=success >> $GITHUB_OUTPUT"
